package org.atcgroup.mcupdater.client.ui.screen;

import org.atcgroup.mcupdater.client.ui.UI;
import org.atcraftmc.updater.client.ClientBootstrap;
import org.atcgroup.mcupdater.client.ui.component.ImagePanel;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

public final class StartScreen extends Screen {
    private ImagePanel clientIcon;
    private JPanel root;
    private JLabel clientName;

    private void createUIComponents() {
        this.clientIcon = new ImagePanel();
        this.clientIcon.paintImage(UI.image("/icon.png"));
    }

    public StartScreen() {
        $$$setupUI$$$();
        this.clientName.setText(ClientBootstrap.config().brand());
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        root = new JPanel();
        root.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        panel1.setEnabled(true);
        panel1.setMaximumSize(new Dimension(200, 200));
        root.add(panel1, BorderLayout.CENTER);
        clientIcon.setMaximumSize(new Dimension(140, 140));
        clientIcon.setMinimumSize(new Dimension(140, 140));
        clientIcon.setPreferredSize(new Dimension(140, 140));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        gbc.insets = new Insets(0, 0, 16, 0);
        panel1.add(clientIcon, gbc);
        clientName = new JLabel();
        Font clientNameFont = this.$$$getFont$$$(null, -1, 26, clientName.getFont());
        if (clientNameFont != null) {
            clientName.setFont(clientNameFont);
        }
        clientName.setHorizontalAlignment(0);
        clientName.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 0, 16, 0);
        panel1.add(clientName, gbc);
        final JProgressBar progressBar1 = new JProgressBar();
        progressBar1.setIndeterminate(true);
        progressBar1.setPreferredSize(new Dimension(250, 4));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 0, 114, 0);
        panel1.add(progressBar1, gbc);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) {
            return null;
        }
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(
                font.getFamily(),
                font.getStyle(),
                font.getSize()
        ) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }

}
