package org.atcgroup.mcupdater.client.ui.screen;

import org.atcgroup.mcupdater.client.MCUpdaterClient;
import org.atcgroup.mcupdater.client.ui.UI;
import org.atcgroup.mcupdater.client.ui.component.ImagePanel;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

public final class WelcomeScreen extends Screen {
    private ImagePanel clientIcon;
    private JPanel root;
    private JButton startButton;
    private JButton extraButton;
    private JLabel clientName;
    private ImagePanel background;

    private void createUIComponents() {

    }

    public WelcomeScreen(Runnable next) {
        $$$setupUI$$$();
        this.clientName.setText(MCUpdaterClient.instance().config().brand());
        this.startButton.addActionListener(e -> next.run());
        this.background.paintImage(UI.background());
        this.clientIcon.paintImage(UI.image("/icon.png"));
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        root = new JPanel();
        root.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        panel1.setEnabled(true);
        panel1.setMaximumSize(new Dimension(200, 200));
        root.add(panel1, BorderLayout.WEST);
        clientIcon = new ImagePanel();
        clientIcon.setMaximumSize(new Dimension(140, 140));
        clientIcon.setMinimumSize(new Dimension(140, 140));
        clientIcon.setPreferredSize(new Dimension(120, 120));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        gbc.insets = new Insets(0, 70, 5, 70);
        panel1.add(clientIcon, gbc);
        clientName = new JLabel();
        Font clientNameFont = this.$$$getFont$$$(null, -1, 26, clientName.getFont());
        if (clientNameFont != null) {
            clientName.setFont(clientNameFont);
        }
        clientName.setHorizontalAlignment(0);
        clientName.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 0, 16, 0);
        panel1.add(clientName, gbc);
        startButton = new JButton();
        startButton.setMaximumSize(new Dimension(160, 40));
        startButton.setMinimumSize(new Dimension(160, 40));
        startButton.setPreferredSize(new Dimension(160, 40));
        startButton.setText("开始安装");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.insets = new Insets(0, 0, 8, 0);
        panel1.add(startButton, gbc);
        extraButton = new JButton();
        extraButton.setMaximumSize(new Dimension(160, 40));
        extraButton.setMinimumSize(new Dimension(160, 40));
        extraButton.setPreferredSize(new Dimension(160, 40));
        extraButton.setText("用户协议");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.insets = new Insets(0, 0, 30, 0);
        panel1.add(extraButton, gbc);
        background = new ImagePanel();
        root.add(background, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) {
            return null;
        }
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(
                font.getFamily(),
                font.getStyle(),
                font.getSize()
        ) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }

}
