pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositories {
        google()
        mavenCentral()
        maven {
            url = uri("https://maven.pkg.jetbrains.space/public/p/compose/dev")
        }
    }
}

rootProject.name = 'MCUpdater'
include 'mcu-client'
include 'mcu-server'
include 'mcu-common'
include 'mcu-cdn'
include 'mcu-cdn-velocity-loader'

