plugins {
    id 'java'
}

apply from: "E:/Java/GradleScripts/build-base.gradle"
apply from: "../github-packages.gradle"
apply from: "../gbuild.gradle"

group = 'org.atcraftmc'
version = '1.0-SNAPSHOT'

applyGlobalScript("Publish/ProjectOutput.gradle")
applyGlobalScript("Dependencies.gradle")

repositories {
    mavenCentral()
}

sourceCompatibility = '17'
targetCompatibility = '17'

dependencies {
    implementation gbuildLib("me.gb2022.commons:commons-nbt")
    implementation gbuildLib("me.gb2022.commons:commons-math")
    implementation gbuildLib("me.gb2022.commons:commons-container")
    implementation gbuildLib("me.gb2022.commons:commons-general")

    implementation 'com.google.code.gson:gson:2.12.1'

    compileOnly "org.apache.logging.log4j:log4j-core:2.8.1"
    compileOnly 'io.netty:netty-buffer:4.1.119.Final'
    compileOnly 'io.netty:netty-codec:4.1.119.Final'
    compileOnly 'io.netty:netty-handler:4.1.119.Final'
    compileOnly 'io.netty:netty-transport:4.1.119.Final'

    implementation localStorage('me.gb2022.simpnet.simpnet-base')
}