plugins {
    id 'java'
}

apply from: "../gbuild.gradle"
apply from: "../github-packages.gradle"

group = 'org.atcraftmc'
version = '1.0'

applyGlobalScript("Publish/ProjectOutput.gradle")

repositories {
    mavenCentral()
    papermcRepo()
}

dependencies {
    implementation "org.apache.logging.log4j:log4j-core:2.8.1"
    implementation 'io.netty:netty-buffer:4.1.119.Final'
    implementation 'io.netty:netty-codec:4.1.119.Final'
    implementation 'io.netty:netty-handler:4.1.119.Final'
    implementation 'io.netty:netty-transport:4.1.119.Final'

    compileOnly 'com.velocitypowered:velocity-api:3.4.0-SNAPSHOT'
    annotationProcessor 'com.velocitypowered:velocity-api:3.4.0-SNAPSHOT'
    compileOnly "org.apache.logging.log4j:log4j-api:2.8.1"
    implementation 'org.slf4j:log4j-over-slf4j:2.0.0-alpha1'

    implementation project(":mcu-common")
}

test {
    useJUnitPlatform()
}

jar{
    manifest{
        attributes "Main-Class":"org.atcraftmc.mcupdater.cdn.MCUpdaterCDNServer";
    }
    archiveBaseName="mc-updater-cdn"
    duplicatesStrategy = DuplicatesStrategy.INCLUDE

    from {
        (configurations.runtimeClasspath).collect {
            it.isDirectory() ? it : zipTree(it)
        }
    }
}