package org.atcgroup.mcupdater.client.ui.component;

import org.atcgroup.mcupdater.client.ui.TaskListener;
import org.atcgroup.mcupdater.client.ui.screen.ProcessScreen;

import javax.swing.*;
import java.awt.*;

public final class ExtraTaskCard implements TaskListener {
    private JProgressBar progress;
    private JLabel text;
    private JPanel root;
    private ProcessScreen parent;

    public void setParent(ProcessScreen parent) {
        this.parent = parent;
    }

    @Override
    public void setProgressTitle(String title) {
        this.text.setText(title);
    }

    @Override
    public void setUnsureProgress(String message) {

        SwingUtilities.invokeLater(() -> {
            this.progress.setIndeterminate(true);
            this.text.setText(message);
        });
    }

    @Override
    public void setProgress(int prog) {
        SwingUtilities.invokeLater(() -> {
            this.progress.setIndeterminate(false);
            this.progress.setValue(prog);
        });
    }

    public void close() {
        this.parent.removeTrackingTask(this);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        root = new JPanel();
        root.setLayout(new GridBagLayout());
        progress = new JProgressBar();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(3, 10, 10, 10);
        root.add(progress, gbc);
        text = new JLabel();
        text.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(10, 10, 0, 0);
        root.add(text, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }
}
