package org.atcgroup.mcupdater.client.ui.component;

import org.atcgroup.mcupdater.data.UpdateChannelMeta;
import org.atcgroup.mcupdater.client.ClientInstallationInfo;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

public final class UpdateChannelCard {
    private JLabel name;
    private JLabel desc;
    private JPanel root;
    private JButton selector;
    private boolean status;
    private final ClientInstallationInfo info;

    public UpdateChannelCard(UpdateChannelMeta meta, ClientInstallationInfo info) {
        this.name.setText(meta.name());
        this.desc.setText(meta.desc());
        this.info = info;
        this.status = info.getLocalVersions().containsKey(meta.id());

        if (meta.required()) {
            this.selector.setToolTipText("服务器已强制要求安装此更新包。");
            this.selector.setEnabled(false);
            this.selector.setText("禁用");
            this.status = true;
            this.info.setEnabled(meta.id(), true);
        }

        this.selector.addActionListener(e -> {
            this.status = !this.status;
            this.selector.setText(this.status ? "禁用" : "启用");
            this.info.setEnabled(meta.id(), this.status);
        });

        this.selector.setText(this.status ? "禁用" : "启用");
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        root = new JPanel();
        root.setLayout(new GridBagLayout());
        root.setToolTipText("");
        final JPanel spacer1 = new JPanel();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridheight = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        root.add(spacer1, gbc);
        name = new JLabel();
        Font nameFont = this.$$$getFont$$$(null, -1, 18, name.getFont());
        if (nameFont != null) {
            name.setFont(nameFont);
        }
        name.setText("这是一个更新频道的名称");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        root.add(name, gbc);
        desc = new JLabel();
        Font descFont = this.$$$getFont$$$(null, -1, 12, desc.getFont());
        if (descFont != null) {
            desc.setFont(descFont);
        }
        desc.setText("这是一个更新频道的描述");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        root.add(desc, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        root.add(spacer2, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.VERTICAL;
        root.add(spacer3, gbc);
        selector = new JButton();
        selector.setText("启用");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.gridheight = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        root.add(selector, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        root.add(spacer4, gbc);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) {
            return null;
        }
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(
                font.getFamily(),
                font.getStyle(),
                font.getSize()
        ) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }

}
