plugins {
    id 'java'
}

apply from: "E:/Java/GradleScripts/build-base.gradle"
apply from: "../github-packages.gradle"

group = 'org.atcraftmc'
version = '1.0'

applyGlobalScript("Publish/ProjectOutput.gradle")
applyGlobalScript("Dependencies.gradle")
apply from: "../gbuild.gradle"

repositories {
    mavenCentral()
}

dependencies {
    implementation gbuildLib("me.gb2022.commons:commons-nbt")
    implementation gbuildLib("me.gb2022.commons:commons-math")
    implementation gbuildLib("me.gb2022.commons:commons-container")
    implementation gbuildLib("me.gb2022.commons:commons-general")

    implementation 'com.google.code.gson:gson:2.12.1'

    implementation project(":mcu-common")

    // https://mvnrepository.com/artifact/io.netty/netty-all
    implementation "org.apache.logging.log4j:log4j-core:2.8.1"
    implementation 'io.netty:netty-buffer:4.1.119.Final'
    implementation 'io.netty:netty-codec:4.1.119.Final'
    implementation 'io.netty:netty-handler:4.1.119.Final'
    implementation 'io.netty:netty-transport:4.1.119.Final'
    implementation projectLocal("bukkit-configuration")

    implementation gbuildLib('me.gb2022.simpnet:simpnet-base')
    implementation("org.yaml:snakeyaml:1.19")

    implementation "org.apache.logging.log4j:log4j-core:2.8.1"
}

jar{
    manifest{
        attributes "Main-Class":"org.atcgroup.mcupdater.server.Main";
    }
    archiveBaseName="mc-updater-server"
    duplicatesStrategy = DuplicatesStrategy.INCLUDE

    from {
        (configurations.runtimeClasspath).collect {
            it.isDirectory() ? it : zipTree(it)
        }
    }
}